server:
  port: 8081
  context-path: /system

spring:
  jackon:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://47.103.37.162:3306/car_rental_system?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: seeksdata@123
    driver-class-name: com.mysql.jdbc.Driver

logging:
  config: classpath:logback.xml

swagger:
  enable: true

#mybatis-plus:
#  global-config:
#    id-type: 0
#    db-column-underline: false
#    refresh-mapper: true
#  typeEnumsPackage: com.galaxy.**.enums
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    lazyLoadingEnabled: true
#    multipleResultSetsEnabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl